# Getting started with TensorFlow's Dataset API (continuation)

In this notebook we will create `Dataset` objects from user-defined python generators.

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
tf.version.VERSION

'2.3.0'

In [6]:
def dataset_generator():
    """A data-producing logic"""
    for i in range(5):
        yield np.random.random([4]), i

In [7]:
for i in dataset_generator():
    print(i)

(array([0.20434366, 0.93957865, 0.72931604, 0.28641238]), 0)
(array([0.51670198, 0.18447463, 0.37133608, 0.65037608]), 1)
(array([0.96519324, 0.17997443, 0.05979529, 0.35789654]), 2)
(array([0.63572866, 0.84381697, 0.60400298, 0.91774899]), 3)
(array([0.77901035, 0.87519005, 0.72786191, 0.01469873]), 4)


In [8]:
dataset = tf.data.Dataset.from_generator(dataset_generator, output_types=(tf.float32, tf.int32))

In [9]:
for x, y in dataset:
    print(f'x: {x}    y: {y}')

x: [0.23497358 0.90216744 0.33594283 0.64630884]    y: 0
x: [0.05361236 0.18342438 0.28807425 0.22552526]    y: 1
x: [0.694196   0.4117361  0.8408844  0.28330523]    y: 2
x: [0.21889393 0.7696549  0.1720058  0.43824056]    y: 3
x: [0.4105971  0.7061228  0.03912476 0.5294592 ]    y: 4


In [10]:
def dataset_generator():
    """A data-producing logic"""
    for i in range(5):
        yield {'features': np.random.random([4]), 'label': i}

In [13]:
dataset = tf.data.Dataset.from_generator(dataset_generator, output_types=({'features': tf.float32,
                                                                           'label':tf.int32}))

In [14]:
for d in dataset:
    print(f"x: {d['features']}    y: {d['label']}")

x: [0.47586858 0.926668   0.28587663 0.3494693 ]    y: 0
x: [0.6354029  0.10374387 0.02920051 0.8872098 ]    y: 1
x: [0.7966424  0.00458661 0.09531031 0.8150314 ]    y: 2
x: [0.8333806  0.33251214 0.66171455 0.30316237]    y: 3
x: [0.53847075 0.07982261 0.94400954 0.5500703 ]    y: 4
