# Getting started with TensorFlow's Dataset API (continuation)

In this notebook we will create `Dataset` objects from user-defined python generators.

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
tf.version.VERSION

'2.3.0'

In [3]:
def dataset_generator():
    """A data-producing logic"""
    for i in range(5):
        yield np.random.random([4]), i

In [4]:
for i in dataset_generator():
    print(i)

(array([0.87456716, 0.23032953, 0.69284068, 0.54633986]), 0)
(array([0.87021991, 0.24472265, 0.91690982, 0.46777818]), 1)
(array([0.13773718, 0.62813327, 0.6790999 , 0.8163329 ]), 2)
(array([0.70663585, 0.74519989, 0.13937979, 0.22368679]), 3)
(array([0.18629237, 0.08442036, 0.91339327, 0.99652987]), 4)


In [5]:
dataset = tf.data.Dataset.from_generator(dataset_generator, output_types=(tf.float32, tf.int32))

In [6]:
for x, y in dataset:
    print(f'x: {x}    y: {y}')

x: [0.9531401  0.1637671  0.43931857 0.03971878]    y: 0
x: [0.37731084 0.4367413  0.5265609  0.81698495]    y: 1
x: [0.48564202 0.74603015 0.28086534 0.5849274 ]    y: 2
x: [0.780176   0.7990948  0.36120576 0.0810954 ]    y: 3
x: [0.1670886  0.04537757 0.9082585  0.79098845]    y: 4


In [7]:
def dataset_generator():
    """A data-producing logic"""
    for i in range(5):
        yield {'features': np.random.random([4]), 'label': i}

In [8]:
dataset = tf.data.Dataset.from_generator(dataset_generator, output_types=({'features': tf.float32,
                                                                           'label':tf.int32}))

In [9]:
for d in dataset:
    print(f"x: {d['features']}    y: {d['label']}")

x: [0.5607467  0.99109644 0.68711835 0.57447654]    y: 0
x: [0.7089115  0.1641704  0.5622395  0.29164907]    y: 1
x: [0.31427646 0.01060347 0.7128158  0.6603938 ]    y: 2
x: [0.34966183 0.18073791 0.5192959  0.6736021 ]    y: 3
x: [0.21184993 0.5777269  0.99364007 0.7721713 ]    y: 4
