# Getting started with TensorFlow's Dataset API (continuation)

In this notebook we will contruct `Dataset` objects from user-defined python generators.

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
tf.version.VERSION

'2.3.0'

In [23]:
def dataset_generator():
    """A data-producing logic"""
    for i in range(5):
        yield (np.random.random([4]), i)

In [24]:
for i in dataset_generator():
    print(i)

(array([0.93543086, 0.79028275, 0.30008644, 0.79888733]), 0)
(array([0.23012207, 0.87688122, 0.13276602, 0.22290542]), 1)
(array([0.83520467, 0.34035547, 0.32658274, 0.32058185]), 2)
(array([0.55204264, 0.44405763, 0.98990695, 0.06689118]), 3)
(array([0.44074843, 0.47680804, 0.22460333, 0.27939454]), 4)


In [26]:
dataset = tf.data.Dataset.from_generator(dataset_generator, output_types=(tf.float32, tf.int32))

In [29]:
for x, y in dataset:
    print(f'x: {x}    y: {y}')

x: [0.23803176 0.30944932 0.6542182  0.9589151 ]    y: 0
x: [0.31767222 0.15838544 0.94264376 0.85219955]    y: 1
x: [0.00120892 0.7665016  0.53363156 0.04406581]    y: 2
x: [0.8155043  0.17091843 0.4040227  0.51903886]    y: 3
x: [9.9333680e-05 5.7572919e-01 8.4651721e-01 2.5559947e-01]    y: 4


In [30]:
def dataset_generator():
    """A data-producing logic"""
    for i in range(5):
        yield {'features': np.random.random([4]), 'label': i}

In [35]:
dataset = tf.data.Dataset.from_generator(dataset_generator, output_types=({'features': tf.float32,
                                                                           'label':tf.int32}))
dataset = dataset.repeat(2)

In [36]:
for d in dataset:
    print(f"x: {d['features']}    y: {d['label']}")

x: [0.5871347  0.15358329 0.6902823  0.12933145]    y: 0
x: [0.8722853 0.4654394 0.8680336 0.9532194]    y: 1
x: [0.4417006  0.16007094 0.37262976 0.23263507]    y: 2
x: [0.34699956 0.35316643 0.07121193 0.87599456]    y: 3
x: [0.83371764 0.17694283 0.38864917 0.3720382 ]    y: 4
x: [0.8510982 0.4970539 0.8101627 0.9634722]    y: 0
x: [0.51277435 0.7549656  0.04172024 0.04326453]    y: 1
x: [0.12037944 0.42405838 0.00157191 0.37740716]    y: 2
x: [0.2490515  0.6715257  0.75464946 0.7888735 ]    y: 3
x: [0.08564515 0.9242153  0.4854496  0.3513795 ]    y: 4
