# Getting started with TensorFlow's Dataset API (continuation)

In this notebook we will contruct `Dataset` objects from user-defined python generators.

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
tf.VERSION

'1.12.0'

In [3]:
def dataset_generator():
    """A data-producing logic"""
    for i in range(10):
        yield (np.random.random([4]), i)

In [4]:
for i in dataset_generator():
    print(i)

(array([0.21413736, 0.89962114, 0.34717722, 0.97837365]), 0)
(array([0.62102295, 0.33700377, 0.53802452, 0.34527054]), 1)
(array([0.51957053, 0.62097398, 0.91608426, 0.92252281]), 2)
(array([0.02989156, 0.06414512, 0.32852923, 0.43791131]), 3)
(array([0.87601812, 0.86209492, 0.06721322, 0.05266822]), 4)
(array([0.61676657, 0.56429246, 0.49519676, 0.49357635]), 5)
(array([0.85268642, 0.16021559, 0.81421868, 0.16235602]), 6)
(array([0.21927717, 0.02578873, 0.16926137, 0.57791297]), 7)
(array([0.45441587, 0.55781128, 0.99524347, 0.53489464]), 8)
(array([0.00911221, 0.327556  , 0.4837321 , 0.77481133]), 9)


In [5]:
dataset = tf.data.Dataset.from_generator(dataset_generator, output_types=(tf.float32, tf.int32))
iterator = dataset.make_one_shot_iterator()
next_item = iterator.get_next()

In [6]:
with tf.Session() as sess:
    try:
        for i in range(10):
            features, label = sess.run(next_item)
            print('features: %s  |  label: %s' % (features, label))
    except tf.errors.OutOfRangeError:
        print('The dataset ran out of entries!')

features: [0.4389241  0.658306   0.34342068 0.8127252 ]  |  label: 0
features: [0.70937    0.6801202  0.75700814 0.86524224]  |  label: 1
features: [0.9636134 0.5067894 0.3817933 0.4132153]  |  label: 2
features: [0.87226754 0.01352761 0.8667968  0.75782055]  |  label: 3
features: [0.7409936  0.2437395  0.4855215  0.17426667]  |  label: 4
features: [0.2923314  0.7469865  0.22834536 0.44102287]  |  label: 5
features: [0.2684892  0.19937906 0.5534683  0.33727953]  |  label: 6
features: [0.36276948 0.77746344 0.00196521 0.9983215 ]  |  label: 7
features: [0.76171285 0.7799833  0.08518038 0.9035363 ]  |  label: 8
features: [0.0389096 0.8985986 0.5428115 0.3832675]  |  label: 9


In [7]:
def dataset_generator():
    """A data-producing logic"""
    for i in range(10):
        yield {'features': np.random.random([4]), 'label': i}

In [8]:
dataset = tf.data.Dataset.from_generator(dataset_generator, output_types=({'features': tf.float32,
                                                                           'label':tf.int32}))
dataset = dataset.repeat()
iterator = dataset.make_one_shot_iterator()
next_item = iterator.get_next()

In [9]:
with tf.Session() as sess:
    try:
        for i in range(10):
            entry = sess.run(next_item)
            print('features: %s  |  label: %s' % (entry['features'], entry['label']))
    except tf.errors.OutOfRangeError:
        print('The dataset ran out of entries!')

features: [0.12664254 0.24528153 0.8929983  0.251323  ]  |  label: 0
features: [0.60858345 0.31532422 0.2696976  0.8578767 ]  |  label: 1
features: [0.53078467 0.19051754 0.41963285 0.4426176 ]  |  label: 2
features: [0.20061171 0.6182147  0.80167514 0.8960162 ]  |  label: 3
features: [0.42585117 0.50923234 0.26869646 0.7943657 ]  |  label: 4
features: [0.0780185  0.92577285 0.84408784 0.4917763 ]  |  label: 5
features: [0.2066731  0.8235747  0.96834207 0.89794326]  |  label: 6
features: [0.8967705  0.11389095 0.9752993  0.04319047]  |  label: 7
features: [0.35424942 0.51549697 0.67195696 0.97359014]  |  label: 8
features: [0.40732422 0.75835764 0.77130884 0.19294138]  |  label: 9
